### ISSUE TITLE
MM Hunter Issue

### ISSUE THREAD

**Issue by dsblack115** [Aethys256/AethysRotation#12]
When I switched from BM to MM, the buttons disappeared and nothing I have tried has brought them back.  Screenshots will be attached to show what happens when I unlock.  And even though it was unlocked, it is unmovable.  It has something to do with my hunter because when I logged into my rogue to check, they were showing as normal.  
![wowscrnshot_031217_031031](https://cloud.githubusercontent.com/assets/22847171/23829816/d766b762-06d1-11e7-93ef-6e4b8629e614.jpg)
![wowscrnshot_031217_031043](https://cloud.githubusercontent.com/assets/22847171/23829815/d7660682-06d1-11e7-8b80-bd2876c994b3.jpg)

**Comment by dsblack115** [comment]
Also, just to add, when unlocking, it is not movable.

**Comment by dsblack115** [comment]
Update, my apologies... I should read the complete addon description which does not include MM.  Though I do see it in the code, but not yet released.

**Comment by Aethys256** [comment]
It's okay @dsblack115, @Nianel is working on it and it should be released soonTM ! 😄
