### ISSUE TITLE
Window close sound on ppl joining group/leaving group

### ISSUE THREAD

**Issue by trininja2k** [Aethys256/AethysRotation#15]
As mentioned on Discord the window close sound is popping up all the time when ppl leave or join the group. You mentioned something about the Artifact Scan and that I should open a ticket. Here you go. ;)

**Comment by Aethys256** [comment]
From https://mods.curse.com/addons/wow/aethysrotation?comment=18:

> Aisenfaire
Posted Mar 9, 2017

Hi,
 
Something weird:  whenever I have this addon enabled, I keep randomly hearing the sound of a UI window being closed (like for example if you closed the artifact window).  It doesn't happen in combat (it's possible it just got drowned out by combat noise but I don't think so), but out of combat it keeps randomly playing with some frequency.
 
Also, the talent window immediately closes after I change 1 talent (while this addon is enabled).
