### ISSUE TITLE
cd/aoe/on/off toggle buttons disappearing

### ISSUE THREAD

**Issue by mynameisdan** [Aethys256/AethysRotation#7]
The cd/aoe/on/off toggle buttons seem to disappear permanently if I log into a class that is unsupported (Frost dk), and log into a class that is (Sub Rogue).

Reloading, turning it off and on, unlock/lock, nothing seems to bring it back.

Requires complete removal + reinstallation of the addon.

**Comment by Aethys256** [comment]
Fixed in https://github.com/Aethys256/AethysRotation/commit/68e395746f481bbb0817a27489e437fde484013b
I'll make a release for Curse soon.
